version: '3'
services:
  app2: # Changed from 'app' to 'app2'
    build:
      context: .
      dockerfile: Dockerfile
    image: my-service-app2:latest # Changed image name for clarity
    ports:
      - "3001:3000" # Changed host port to 3001 to avoid conflict
