#version: '3.8'
#services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    image: my-service:latest  # Explicitly define the image name






version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-service:latest
    ports:
      - "3001:3001"
